"""empty message

Revision ID: 1f31b7cc5100
Revises: a0aedc6ead5a
Create Date: 2020-12-21 21:18:29.173893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f31b7cc5100'
down_revision = 'a0aedc6ead5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'genre_id')
    # ### end Alembic commands ###
